# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.24

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /home/tstone10/tools/cmake-3.24.0-linux-x86_64/bin/cmake

# The command to remove a file.
RM = /home/tstone10/tools/cmake-3.24.0-linux-x86_64/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/tstone10/sgn/upw/bbserver

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/tstone10/sgn/upw/bbserver

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/home/tstone10/tools/cmake-3.24.0-linux-x86_64/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/home/tstone10/tools/cmake-3.24.0-linux-x86_64/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/tstone10/sgn/upw/bbserver/CMakeFiles /home/tstone10/sgn/upw/bbserver//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/tstone10/sgn/upw/bbserver/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named BBServer

# Build rule for target.
BBServer: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 BBServer
.PHONY : BBServer

# fast build rule for target.
BBServer/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BBServer.dir/build.make CMakeFiles/BBServer.dir/build
.PHONY : BBServer/fast

ClientManager.o: ClientManager.cpp.o
.PHONY : ClientManager.o

# target to build an object file
ClientManager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BBServer.dir/build.make CMakeFiles/BBServer.dir/ClientManager.cpp.o
.PHONY : ClientManager.cpp.o

ClientManager.i: ClientManager.cpp.i
.PHONY : ClientManager.i

# target to preprocess a source file
ClientManager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BBServer.dir/build.make CMakeFiles/BBServer.dir/ClientManager.cpp.i
.PHONY : ClientManager.cpp.i

ClientManager.s: ClientManager.cpp.s
.PHONY : ClientManager.s

# target to generate assembly for a file
ClientManager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BBServer.dir/build.make CMakeFiles/BBServer.dir/ClientManager.cpp.s
.PHONY : ClientManager.cpp.s

ConfigManager.o: ConfigManager.cpp.o
.PHONY : ConfigManager.o

# target to build an object file
ConfigManager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BBServer.dir/build.make CMakeFiles/BBServer.dir/ConfigManager.cpp.o
.PHONY : ConfigManager.cpp.o

ConfigManager.i: ConfigManager.cpp.i
.PHONY : ConfigManager.i

# target to preprocess a source file
ConfigManager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BBServer.dir/build.make CMakeFiles/BBServer.dir/ConfigManager.cpp.i
.PHONY : ConfigManager.cpp.i

ConfigManager.s: ConfigManager.cpp.s
.PHONY : ConfigManager.s

# target to generate assembly for a file
ConfigManager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BBServer.dir/build.make CMakeFiles/BBServer.dir/ConfigManager.cpp.s
.PHONY : ConfigManager.cpp.s

Constants.o: Constants.cpp.o
.PHONY : Constants.o

# target to build an object file
Constants.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BBServer.dir/build.make CMakeFiles/BBServer.dir/Constants.cpp.o
.PHONY : Constants.cpp.o

Constants.i: Constants.cpp.i
.PHONY : Constants.i

# target to preprocess a source file
Constants.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BBServer.dir/build.make CMakeFiles/BBServer.dir/Constants.cpp.i
.PHONY : Constants.cpp.i

Constants.s: Constants.cpp.s
.PHONY : Constants.s

# target to generate assembly for a file
Constants.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BBServer.dir/build.make CMakeFiles/BBServer.dir/Constants.cpp.s
.PHONY : Constants.cpp.s

FileLogger.o: FileLogger.cpp.o
.PHONY : FileLogger.o

# target to build an object file
FileLogger.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BBServer.dir/build.make CMakeFiles/BBServer.dir/FileLogger.cpp.o
.PHONY : FileLogger.cpp.o

FileLogger.i: FileLogger.cpp.i
.PHONY : FileLogger.i

# target to preprocess a source file
FileLogger.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BBServer.dir/build.make CMakeFiles/BBServer.dir/FileLogger.cpp.i
.PHONY : FileLogger.cpp.i

FileLogger.s: FileLogger.cpp.s
.PHONY : FileLogger.s

# target to generate assembly for a file
FileLogger.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BBServer.dir/build.make CMakeFiles/BBServer.dir/FileLogger.cpp.s
.PHONY : FileLogger.cpp.s

FileManager.o: FileManager.cpp.o
.PHONY : FileManager.o

# target to build an object file
FileManager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BBServer.dir/build.make CMakeFiles/BBServer.dir/FileManager.cpp.o
.PHONY : FileManager.cpp.o

FileManager.i: FileManager.cpp.i
.PHONY : FileManager.i

# target to preprocess a source file
FileManager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BBServer.dir/build.make CMakeFiles/BBServer.dir/FileManager.cpp.i
.PHONY : FileManager.cpp.i

FileManager.s: FileManager.cpp.s
.PHONY : FileManager.s

# target to generate assembly for a file
FileManager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BBServer.dir/build.make CMakeFiles/BBServer.dir/FileManager.cpp.s
.PHONY : FileManager.cpp.s

Protocol.o: Protocol.cpp.o
.PHONY : Protocol.o

# target to build an object file
Protocol.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BBServer.dir/build.make CMakeFiles/BBServer.dir/Protocol.cpp.o
.PHONY : Protocol.cpp.o

Protocol.i: Protocol.cpp.i
.PHONY : Protocol.i

# target to preprocess a source file
Protocol.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BBServer.dir/build.make CMakeFiles/BBServer.dir/Protocol.cpp.i
.PHONY : Protocol.cpp.i

Protocol.s: Protocol.cpp.s
.PHONY : Protocol.s

# target to generate assembly for a file
Protocol.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BBServer.dir/build.make CMakeFiles/BBServer.dir/Protocol.cpp.s
.PHONY : Protocol.cpp.s

SGNServer_01.o: SGNServer_01.cpp.o
.PHONY : SGNServer_01.o

# target to build an object file
SGNServer_01.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BBServer.dir/build.make CMakeFiles/BBServer.dir/SGNServer_01.cpp.o
.PHONY : SGNServer_01.cpp.o

SGNServer_01.i: SGNServer_01.cpp.i
.PHONY : SGNServer_01.i

# target to preprocess a source file
SGNServer_01.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BBServer.dir/build.make CMakeFiles/BBServer.dir/SGNServer_01.cpp.i
.PHONY : SGNServer_01.cpp.i

SGNServer_01.s: SGNServer_01.cpp.s
.PHONY : SGNServer_01.s

# target to generate assembly for a file
SGNServer_01.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BBServer.dir/build.make CMakeFiles/BBServer.dir/SGNServer_01.cpp.s
.PHONY : SGNServer_01.cpp.s

StateMachine.o: StateMachine.cpp.o
.PHONY : StateMachine.o

# target to build an object file
StateMachine.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BBServer.dir/build.make CMakeFiles/BBServer.dir/StateMachine.cpp.o
.PHONY : StateMachine.cpp.o

StateMachine.i: StateMachine.cpp.i
.PHONY : StateMachine.i

# target to preprocess a source file
StateMachine.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BBServer.dir/build.make CMakeFiles/BBServer.dir/StateMachine.cpp.i
.PHONY : StateMachine.cpp.i

StateMachine.s: StateMachine.cpp.s
.PHONY : StateMachine.s

# target to generate assembly for a file
StateMachine.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BBServer.dir/build.make CMakeFiles/BBServer.dir/StateMachine.cpp.s
.PHONY : StateMachine.cpp.s

TCPManager.o: TCPManager.cpp.o
.PHONY : TCPManager.o

# target to build an object file
TCPManager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BBServer.dir/build.make CMakeFiles/BBServer.dir/TCPManager.cpp.o
.PHONY : TCPManager.cpp.o

TCPManager.i: TCPManager.cpp.i
.PHONY : TCPManager.i

# target to preprocess a source file
TCPManager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BBServer.dir/build.make CMakeFiles/BBServer.dir/TCPManager.cpp.i
.PHONY : TCPManager.cpp.i

TCPManager.s: TCPManager.cpp.s
.PHONY : TCPManager.s

# target to generate assembly for a file
TCPManager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BBServer.dir/build.make CMakeFiles/BBServer.dir/TCPManager.cpp.s
.PHONY : TCPManager.cpp.s

Timer.o: Timer.cpp.o
.PHONY : Timer.o

# target to build an object file
Timer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BBServer.dir/build.make CMakeFiles/BBServer.dir/Timer.cpp.o
.PHONY : Timer.cpp.o

Timer.i: Timer.cpp.i
.PHONY : Timer.i

# target to preprocess a source file
Timer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BBServer.dir/build.make CMakeFiles/BBServer.dir/Timer.cpp.i
.PHONY : Timer.cpp.i

Timer.s: Timer.cpp.s
.PHONY : Timer.s

# target to generate assembly for a file
Timer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BBServer.dir/build.make CMakeFiles/BBServer.dir/Timer.cpp.s
.PHONY : Timer.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... BBServer"
	@echo "... ClientManager.o"
	@echo "... ClientManager.i"
	@echo "... ClientManager.s"
	@echo "... ConfigManager.o"
	@echo "... ConfigManager.i"
	@echo "... ConfigManager.s"
	@echo "... Constants.o"
	@echo "... Constants.i"
	@echo "... Constants.s"
	@echo "... FileLogger.o"
	@echo "... FileLogger.i"
	@echo "... FileLogger.s"
	@echo "... FileManager.o"
	@echo "... FileManager.i"
	@echo "... FileManager.s"
	@echo "... Protocol.o"
	@echo "... Protocol.i"
	@echo "... Protocol.s"
	@echo "... SGNServer_01.o"
	@echo "... SGNServer_01.i"
	@echo "... SGNServer_01.s"
	@echo "... StateMachine.o"
	@echo "... StateMachine.i"
	@echo "... StateMachine.s"
	@echo "... TCPManager.o"
	@echo "... TCPManager.i"
	@echo "... TCPManager.s"
	@echo "... Timer.o"
	@echo "... Timer.i"
	@echo "... Timer.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

