# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.24

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /home/tstone10/tools/cmake-3.24.0-linux-x86_64/bin/cmake

# The command to remove a file.
RM = /home/tstone10/tools/cmake-3.24.0-linux-x86_64/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/tstone10/sgn/upw/bbserver

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/tstone10/sgn/upw/bbserver

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/home/tstone10/tools/cmake-3.24.0-linux-x86_64/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/home/tstone10/tools/cmake-3.24.0-linux-x86_64/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/tstone10/sgn/upw/bbserver/CMakeFiles /home/tstone10/sgn/upw/bbserver//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/tstone10/sgn/upw/bbserver/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named BBServer

# Build rule for target.
BBServer: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 BBServer
.PHONY : BBServer

# fast build rule for target.
BBServer/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BBServer.dir/build.make CMakeFiles/BBServer.dir/build
.PHONY : BBServer/fast

src/ClientManager.o: src/ClientManager.cpp.o
.PHONY : src/ClientManager.o

# target to build an object file
src/ClientManager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BBServer.dir/build.make CMakeFiles/BBServer.dir/src/ClientManager.cpp.o
.PHONY : src/ClientManager.cpp.o

src/ClientManager.i: src/ClientManager.cpp.i
.PHONY : src/ClientManager.i

# target to preprocess a source file
src/ClientManager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BBServer.dir/build.make CMakeFiles/BBServer.dir/src/ClientManager.cpp.i
.PHONY : src/ClientManager.cpp.i

src/ClientManager.s: src/ClientManager.cpp.s
.PHONY : src/ClientManager.s

# target to generate assembly for a file
src/ClientManager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BBServer.dir/build.make CMakeFiles/BBServer.dir/src/ClientManager.cpp.s
.PHONY : src/ClientManager.cpp.s

src/ConfigManager.o: src/ConfigManager.cpp.o
.PHONY : src/ConfigManager.o

# target to build an object file
src/ConfigManager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BBServer.dir/build.make CMakeFiles/BBServer.dir/src/ConfigManager.cpp.o
.PHONY : src/ConfigManager.cpp.o

src/ConfigManager.i: src/ConfigManager.cpp.i
.PHONY : src/ConfigManager.i

# target to preprocess a source file
src/ConfigManager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BBServer.dir/build.make CMakeFiles/BBServer.dir/src/ConfigManager.cpp.i
.PHONY : src/ConfigManager.cpp.i

src/ConfigManager.s: src/ConfigManager.cpp.s
.PHONY : src/ConfigManager.s

# target to generate assembly for a file
src/ConfigManager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BBServer.dir/build.make CMakeFiles/BBServer.dir/src/ConfigManager.cpp.s
.PHONY : src/ConfigManager.cpp.s

src/Constants.o: src/Constants.cpp.o
.PHONY : src/Constants.o

# target to build an object file
src/Constants.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BBServer.dir/build.make CMakeFiles/BBServer.dir/src/Constants.cpp.o
.PHONY : src/Constants.cpp.o

src/Constants.i: src/Constants.cpp.i
.PHONY : src/Constants.i

# target to preprocess a source file
src/Constants.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BBServer.dir/build.make CMakeFiles/BBServer.dir/src/Constants.cpp.i
.PHONY : src/Constants.cpp.i

src/Constants.s: src/Constants.cpp.s
.PHONY : src/Constants.s

# target to generate assembly for a file
src/Constants.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BBServer.dir/build.make CMakeFiles/BBServer.dir/src/Constants.cpp.s
.PHONY : src/Constants.cpp.s

src/FileLogger.o: src/FileLogger.cpp.o
.PHONY : src/FileLogger.o

# target to build an object file
src/FileLogger.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BBServer.dir/build.make CMakeFiles/BBServer.dir/src/FileLogger.cpp.o
.PHONY : src/FileLogger.cpp.o

src/FileLogger.i: src/FileLogger.cpp.i
.PHONY : src/FileLogger.i

# target to preprocess a source file
src/FileLogger.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BBServer.dir/build.make CMakeFiles/BBServer.dir/src/FileLogger.cpp.i
.PHONY : src/FileLogger.cpp.i

src/FileLogger.s: src/FileLogger.cpp.s
.PHONY : src/FileLogger.s

# target to generate assembly for a file
src/FileLogger.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BBServer.dir/build.make CMakeFiles/BBServer.dir/src/FileLogger.cpp.s
.PHONY : src/FileLogger.cpp.s

src/FileManager.o: src/FileManager.cpp.o
.PHONY : src/FileManager.o

# target to build an object file
src/FileManager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BBServer.dir/build.make CMakeFiles/BBServer.dir/src/FileManager.cpp.o
.PHONY : src/FileManager.cpp.o

src/FileManager.i: src/FileManager.cpp.i
.PHONY : src/FileManager.i

# target to preprocess a source file
src/FileManager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BBServer.dir/build.make CMakeFiles/BBServer.dir/src/FileManager.cpp.i
.PHONY : src/FileManager.cpp.i

src/FileManager.s: src/FileManager.cpp.s
.PHONY : src/FileManager.s

# target to generate assembly for a file
src/FileManager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BBServer.dir/build.make CMakeFiles/BBServer.dir/src/FileManager.cpp.s
.PHONY : src/FileManager.cpp.s

src/Protocol.o: src/Protocol.cpp.o
.PHONY : src/Protocol.o

# target to build an object file
src/Protocol.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BBServer.dir/build.make CMakeFiles/BBServer.dir/src/Protocol.cpp.o
.PHONY : src/Protocol.cpp.o

src/Protocol.i: src/Protocol.cpp.i
.PHONY : src/Protocol.i

# target to preprocess a source file
src/Protocol.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BBServer.dir/build.make CMakeFiles/BBServer.dir/src/Protocol.cpp.i
.PHONY : src/Protocol.cpp.i

src/Protocol.s: src/Protocol.cpp.s
.PHONY : src/Protocol.s

# target to generate assembly for a file
src/Protocol.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BBServer.dir/build.make CMakeFiles/BBServer.dir/src/Protocol.cpp.s
.PHONY : src/Protocol.cpp.s

src/SGNServer_01.o: src/SGNServer_01.cpp.o
.PHONY : src/SGNServer_01.o

# target to build an object file
src/SGNServer_01.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BBServer.dir/build.make CMakeFiles/BBServer.dir/src/SGNServer_01.cpp.o
.PHONY : src/SGNServer_01.cpp.o

src/SGNServer_01.i: src/SGNServer_01.cpp.i
.PHONY : src/SGNServer_01.i

# target to preprocess a source file
src/SGNServer_01.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BBServer.dir/build.make CMakeFiles/BBServer.dir/src/SGNServer_01.cpp.i
.PHONY : src/SGNServer_01.cpp.i

src/SGNServer_01.s: src/SGNServer_01.cpp.s
.PHONY : src/SGNServer_01.s

# target to generate assembly for a file
src/SGNServer_01.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BBServer.dir/build.make CMakeFiles/BBServer.dir/src/SGNServer_01.cpp.s
.PHONY : src/SGNServer_01.cpp.s

src/StateMachine.o: src/StateMachine.cpp.o
.PHONY : src/StateMachine.o

# target to build an object file
src/StateMachine.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BBServer.dir/build.make CMakeFiles/BBServer.dir/src/StateMachine.cpp.o
.PHONY : src/StateMachine.cpp.o

src/StateMachine.i: src/StateMachine.cpp.i
.PHONY : src/StateMachine.i

# target to preprocess a source file
src/StateMachine.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BBServer.dir/build.make CMakeFiles/BBServer.dir/src/StateMachine.cpp.i
.PHONY : src/StateMachine.cpp.i

src/StateMachine.s: src/StateMachine.cpp.s
.PHONY : src/StateMachine.s

# target to generate assembly for a file
src/StateMachine.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BBServer.dir/build.make CMakeFiles/BBServer.dir/src/StateMachine.cpp.s
.PHONY : src/StateMachine.cpp.s

src/TCPManager.o: src/TCPManager.cpp.o
.PHONY : src/TCPManager.o

# target to build an object file
src/TCPManager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BBServer.dir/build.make CMakeFiles/BBServer.dir/src/TCPManager.cpp.o
.PHONY : src/TCPManager.cpp.o

src/TCPManager.i: src/TCPManager.cpp.i
.PHONY : src/TCPManager.i

# target to preprocess a source file
src/TCPManager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BBServer.dir/build.make CMakeFiles/BBServer.dir/src/TCPManager.cpp.i
.PHONY : src/TCPManager.cpp.i

src/TCPManager.s: src/TCPManager.cpp.s
.PHONY : src/TCPManager.s

# target to generate assembly for a file
src/TCPManager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BBServer.dir/build.make CMakeFiles/BBServer.dir/src/TCPManager.cpp.s
.PHONY : src/TCPManager.cpp.s

src/Timer.o: src/Timer.cpp.o
.PHONY : src/Timer.o

# target to build an object file
src/Timer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BBServer.dir/build.make CMakeFiles/BBServer.dir/src/Timer.cpp.o
.PHONY : src/Timer.cpp.o

src/Timer.i: src/Timer.cpp.i
.PHONY : src/Timer.i

# target to preprocess a source file
src/Timer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BBServer.dir/build.make CMakeFiles/BBServer.dir/src/Timer.cpp.i
.PHONY : src/Timer.cpp.i

src/Timer.s: src/Timer.cpp.s
.PHONY : src/Timer.s

# target to generate assembly for a file
src/Timer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BBServer.dir/build.make CMakeFiles/BBServer.dir/src/Timer.cpp.s
.PHONY : src/Timer.cpp.s

src/UDPManager.o: src/UDPManager.cpp.o
.PHONY : src/UDPManager.o

# target to build an object file
src/UDPManager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BBServer.dir/build.make CMakeFiles/BBServer.dir/src/UDPManager.cpp.o
.PHONY : src/UDPManager.cpp.o

src/UDPManager.i: src/UDPManager.cpp.i
.PHONY : src/UDPManager.i

# target to preprocess a source file
src/UDPManager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BBServer.dir/build.make CMakeFiles/BBServer.dir/src/UDPManager.cpp.i
.PHONY : src/UDPManager.cpp.i

src/UDPManager.s: src/UDPManager.cpp.s
.PHONY : src/UDPManager.s

# target to generate assembly for a file
src/UDPManager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BBServer.dir/build.make CMakeFiles/BBServer.dir/src/UDPManager.cpp.s
.PHONY : src/UDPManager.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... BBServer"
	@echo "... src/ClientManager.o"
	@echo "... src/ClientManager.i"
	@echo "... src/ClientManager.s"
	@echo "... src/ConfigManager.o"
	@echo "... src/ConfigManager.i"
	@echo "... src/ConfigManager.s"
	@echo "... src/Constants.o"
	@echo "... src/Constants.i"
	@echo "... src/Constants.s"
	@echo "... src/FileLogger.o"
	@echo "... src/FileLogger.i"
	@echo "... src/FileLogger.s"
	@echo "... src/FileManager.o"
	@echo "... src/FileManager.i"
	@echo "... src/FileManager.s"
	@echo "... src/Protocol.o"
	@echo "... src/Protocol.i"
	@echo "... src/Protocol.s"
	@echo "... src/SGNServer_01.o"
	@echo "... src/SGNServer_01.i"
	@echo "... src/SGNServer_01.s"
	@echo "... src/StateMachine.o"
	@echo "... src/StateMachine.i"
	@echo "... src/StateMachine.s"
	@echo "... src/TCPManager.o"
	@echo "... src/TCPManager.i"
	@echo "... src/TCPManager.s"
	@echo "... src/Timer.o"
	@echo "... src/Timer.i"
	@echo "... src/Timer.s"
	@echo "... src/UDPManager.o"
	@echo "... src/UDPManager.i"
	@echo "... src/UDPManager.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

